services:
  - type: web
    name: e4a-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://user:password@cluster.mongodb.net/e4a_db
      - key: JWT_SECRET
        value: your_strong_secret_key_min_32_chars
      - key: NODE_ENV
        value: production
