version: '3.8'
services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017

  backend:
    build: .
    ports:
      - 3000:3000
    environment:
      - MONGODB_URI=mongodb://mongo:27017/e4a_db
      - JWT_SECRET=change_this_secret
    depends_on:
      - mongo
    volumes:
      - ../Frontend:/usr/src/app/Frontend:ro
      - ./src:/usr/src/app/src:rw

volumes:
  mongo-data:
